In [ ]:
import numpy as np

print("NumPy version: ", np.__version__)

# NumPy Arrays: Creating, Accessing, and Modifying

A NumPy array is a grid of values, all of the same data type, which is efficient for data manipulation. It supports multi-dimensional arrays (1D, 2D, and beyond) and allows you to create arrays in various ways (e.g., converting lists, using functions).

## Creating an Array

Consider a small dataset representing information about a group of people, with columns for their age, height, and weight.

In [7]:
import numpy as np

# Sample dataset as a 2D array

data = np.array([
    [25, 175, 70],
    [30, 160, 60],
    [35, 180, 90],
    [40, 170, 80],
    [28, 165, 68]
])

print("Data Array:\n", data)

Data Array:
 [[ 25 175  70]
 [ 30 160  60]
 [ 35 180  90]
 [ 40 170  80]
 [ 28 165  68]]


The array consists of 5 rows and 3 columns. Each inner list represents a row in the array. The elements in each row could represent different features or attributes. Here, each row represents a person, and each column represents:

- Age (in years)
- Height (in centimeters)
- Weight (in kilograms)
- 
Given the data structure above, you can interpret the rows as follows:

- Row 1: A person aged 25 years, with a height of 175 cm and a weight of 70 kg.
- Row 2: A person aged 30 years, with a height of 160 cm and a weight of 60 kg.
- Row 3: A person aged 35 years, with a height of 180 cm and a weight of 90 kg.
- Row 4: A person aged 40 years, with a height of 170 cm and a weight of 80 kg.
- Row 5: A person aged 28 years, with a height of 165 cm and a weight of 68 kg.

## Accessing Elements

In [8]:
age_second_person = data[1,0]
weight_second_person = data[1,2]

print("Age of the second person: ", age_second_person)
print("Weight of the second person: ", weight_second_person)

Age of the second person:  30
Weight of the second person:  60


## Slicing: Extracting Rows, Columns, or Subarrays

### Example 1: Extracting a Column

To extract the 'Height' column (index 1)

In [9]:
heights = data[:,1]
print("Heights: ", heights)

Heights:  [175 160 180 170 165]


#### data[:,1]

- `:` selects all rows
- **1** specifies the colum

### Example 2: Extracting Specific Rows

To extract the ages of the first three people

In [12]:
ages_first_three = data[:3, 0]
print("Ages of the first three people: ", ages_first_three)

ages_second_to_fourth = data[1:4, 0]
print("Ages of 2nd, 3rd and 4th person: ", ages_second_to_fourth)

Ages of the first three people:  [25 30 35]
Ages of 2nd, 3rd and 4th person:  [30 35 40]


#### data[:3, 0]

- `:3` selects rows 0 to 2 (first three rows)
- **0** specifies the column (Age)

#### data[1:4, 0]

- `1:4` selects rows 1 to 3 (second, third and fourth)
- **0** specifies the column (Age)

### Iterating Over Rows in a 2D NumPy Array

Iteration in NumPy allows you to process each row of a 2D array one at a time. This is useful when you want to examine or manipulate data row by row.

#### How Iteration Works

The for loop iterates over the array data, where each iteration retrieves one row. Each row represents a single data entry (e.g., a person's attributes in the dataset)

In [13]:
for person in data:
    print("Person Data:", person)

Person Data: [ 25 175  70]
Person Data: [ 30 160  60]
Person Data: [ 35 180  90]
Person Data: [ 40 170  80]
Person Data: [ 28 165  68]


- **for person in data:** The for loop accesses each row (1D array) in the dataset.
- During each iteration, the variable person holds one row of data, representing the attributes of one individual.
- **print "Person data:", person)** outputs the entire row, making it easy to analyze the data for each person.

#### Practical Use Cases

**Row-by-Row Analysis**: Analyze or manipulate the attributes of each individual

In [15]:
for person in data:
    age, height, weight = person # Unpack the attributes
    print(f"Age: {age}, Height: {height}, Weight: {weight}")

Age: 25, Height: 175, Weight: 70
Age: 30, Height: 160, Weight: 60
Age: 35, Height: 180, Weight: 90
Age: 40, Height: 170, Weight: 80
Age: 28, Height: 165, Weight: 68


## Array Attributes in NumPy

Understanding array properties like shape, size, and dimensions is essential for effective manipulation and understanding of NumPy arrays.

### Array Shape

**ndarray.shape**: The shape of an array refers to its dimensions and is represented as a tuple (rows, columns). Returns a tuple representing the dimensions (shape) of the array.

In [16]:
print("Shape of the array: ", data.shape)

Shape of the array:  (5, 3)


- The dataset has 5 rows (5 individuals) and 3 columns (Age, Height, Weight).
- Shape (5, 3) indicates this structure.

### Array Size ndarray.size: 

The size of an aay refers to the total number of elements in the array. Returns the total number of elements in the array

In [17]:
print("Size of the array: ", data.size)

Size of the array:  15


The array contains 5 rows × 3 columns = 15 elements.

### Array Dimensions (ndim)

**ndarray.ndim**: The number of dimensions (or axes) of an array tells us whether it's a 1D, 2D, or higher-dimensional array. Returns the number of dimensions (axes) of the array.

In [18]:
print("Number of dimensions: ", data.ndim)

Number of dimensions:  2


The dataset is a 2D array because it has rows and columns (Age, Height, and Weight for each individual).

### Data Type (dtype)

**ndarray.dtype**: The data type of an array indicates the type of elements it contains (e.g., integers, floats, etc.). Returns the number of dimensions (axes) of the array.

In [19]:
print("Data type of the array: ", data.dtype)

Data type of the array:  int64


- The elements in the dataset are integers (e.g., ages, heights, and weights).
- NumPy automatically assigned the data type as int64 because all values are integers.

## Mathematical Operations on Arrays: Broadcasting and Vectorized Operations 

In NumPy, mathematical operations can be performed directly on arrays, offering high performance and efficiency. These operations are powered by vectorization and broadcasting, which eliminate the need for explicit loops and allow seamless handling of arrays with different shapes.

### Vectorized Operations
Vectorized operations enable mathematical compelátions dinectly on arrays. These operations are applied element-wise and are highly optimized, ensuring better performance compared to using Python loops.
- **Direct Operations**: You can perform operations (like addition, multiplication, division) directly on arrays.
- **Elticiency**: Operations are applied simultaneously to all elements in the array, leveraging optimized C-basod implementations under the hood.

Example: Converting Heights from om to Meters

To convert the 'Height column in the dataset from centimeters lo meters:

In [20]:
# Converts the heights from cm to meters
heights_in_meters = data[:,1]/100
print("Heights in meters: ", heights_in_meters)

Heights in meters:  [1.75 1.6  1.8  1.7  1.65]


- data[:, 1]: Extracts the second column (Height).
- / 100: Divides each height value by 100 to convert it to meters.

### Reshaping Arrays

Reshaping changes the shape (dimensions) of an array while preserving its data. Commonly used when reorganizing data for model input, preparing matrices for computations, or aligning data dimensions. The total number of elements in the array must remain the same.

Example: Reshaping an Array

In [21]:
reshaped_data = data.reshape(3,5)
print("Reshaped Array (3x5):\n", reshaped_data)

Reshaped Array (3x5):
 [[ 25 175  70  30 160]
 [ 60  35 180  90  40]
 [170  80  28 165  68]]


- data.reshape(3, 5): The original array is reshaped into 3 rows and 5 columns.
- The total number of elements remains 15 (since 5x3 = 3x5).

### Transposing Arrays

Transposing flips an array's rows and columns. Widely used in linear algebra (e.g., matrix multiplication) and data analysis for reorganizing datasets. No new memory allocation; it simply changes the view of the data.

Example: Transposing an Array

In [22]:
transposed_data = data.T
print("Transposed Array:\n", transposed_data)

Transposed Array:
 [[ 25  30  35  40  28]
 [175 160 180 170 165]
 [ 70  60  90  80  68]]


- data.T: Flips the array, swapping rows and columns.
- Each row in the original array becomes a column in the transposed array, and vice versa.

## Creating Arrays

NumPy makes it easy to create arrays, such as arrays of zeros or ones for initialization or arrays with specific sequences.

### Creating Arrays of Zeros: np.zeros()

The np.zeros() function creates an array filled with zeros.

In [23]:
zeros_array = np.zeros((3,3))
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Creating Arrays of Ones: np.ones()

The np.ones() function creates an array filled with ones.

In [24]:
ones_array = np.ones((3,3))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
